import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { greet } from "child";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "react-i18next";
import Link from "next/link";
import i18nConfig from "../next-i18next.config";

const Home: NextPage = () => {
  const { t } = useTranslation("common");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/" locale="en">
          <a
            style={{ background: "pink", padding: "16px", borderRadius: "4px" }}
          >
            GO TO SERVER SIDE RENDERED PAGE
          </a>
        </Link>
        <h1 style={{ color: "pink" }}>{t("greet")}</h1>
        <p>This page is statically rendered.</p>
        <h3 className={styles.title}>{greet("John", "Doe")}</h3>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "cs", ["common"], i18nConfig)),
      // Will be passed to the page component as props
    },
  };
};

export default Home;
